### ISSUE TITLE
basic-setup 브랜치가 없습니다.

### ISSUE THREAD

**Issue by JsonKim** [reason-seoul/reason-todomvc#1]
README에
> 코드를 직접 작성하고 싶은 분들은 basic-setup 태그를 체크아웃 하세요! 제가 여러분들을 위해 귀찮은 웹 팩 설정을 대신 해드렸답니다.

라는 내용이 있는데 basic-setup 브랜치는 리모트에 없는것 같아서 이슈등록 합니다.

멋진 강좌를 공유해주셔서 정말 감사드립니다.

**Comment by cometkim** [comment]
`basic-setup`은 첫번째 커밋에 대한 태그입니다! `checkout`/`switch` 하실 수 있을거에요
